name: pkgs_github.yaml
comments: Dependency packages deployed from GitHub.

packages:
  i3lock-color:
    repo_url: "https://github.com/Raymo111/i3lock-color.git"
    target_dir: "."
    build_command: "./build.sh && ./install-i3lock-color.sh"
    target_bin: ""
    remove_repo: 1
  