name: pkgs_github.yaml
comments: Dependency packages deployed from GitHub.

packages:
  tty-clock:
    repo_url: "https://github.com/xorg62/tty-clock.git"
    target_dir: "."
    build_command: "make && chmod +x tty-clock"
    target_bin: "/usr/local/bin"
    remove_repo: 1
  