#! /bin/sh

#  ___ ___ _____      ____  __    ___ ___  _  _ ___ ___ ___
# | _ ) __| _ \ \    / /  \/  |  / __/ _ \| \| | __|_ _/ __|
# | _ \__ \  _/\ \/\/ /| |\/| | | (_| (_) | .` | _| | | (_ |
# |___/___/_|   \_/\_/ |_|  |_|  \___\___/|_|\_|_| |___\___|
# AlvinPix: https://github.com/AlvinPix
# Default bspwmrc

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V

xsetroot -cursor_name left_ptr &

bspc config border_width         2
bspc config focused_border_color \#3b4441
bspc config normal_border_color \#bfbfbf
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc rule -a "Google-chrome" desktop='I'
bspc rule -a "firefox" desktop='I'
bspc rule -a "SimpleScreenRecorder" state=floating follow=on

# Auto-Start

nitrogen --restore &
lxappearance &
picom &
${HOME}/.config/polybar/launch.sh --cuts &
